### ISSUE TITLE
Drop support for PHP5, Symfony < 4.4

### ISSUE THREAD

**Issue by tacman** [bordeux/geoname-bundle#13]
PHP5 and Symfony 2 have been dead for a while.  Symfony 3 is at EOL, officially dead in November.

What do you think about bumping the minimum version to PHP 7.4 and Symfony 4.4?  

We could type the private vars, and get rid of some mistakes that are in the code now, such as float/string discrepancies:

```php
    /**
     * @var float
     *
     * @ORM\Column(name="feature_code", type="string", length=10, nullable=true)
     */
    protected $featureCode;

    /**
     * @var float
     *
     * @ORM\Column(name="country_code", type="string", length=2, nullable=true)
     */
    protected $countryCode;
```

I've been bumping all my projects to PHP8, and Symfony 6 will require it, so that's an option, too.

**Comment by bordeux** [comment]
Package have been updated, with version 3.0 all issues have been fixed
