### ISSUE TITLE
New install on symfony fails to import. 

### ISSUE THREAD

**Issue by tiktoor** [bordeux/geoname-bundle#17]
Fails while importing https://download.geonames.org/export/dump/allCountries.zip#allCountries.txt

Environment

- Mac M1
- bin/console -V
Symfony 6.2.11 (env: dev, debug: true)
- mysql -V
mysql  Ver 15.1 Distrib 10.11.3-MariaDB, for osx10.18 (arm64) using  EditLine wrapper

Any ideas?

Thank You!

Steps To reproducs:

1. new symfony
2. composer require bordeux/geoname-bundle
3. php bin/console doctrine:database:create
4. php bin/console doctrine:schema:update --force

[WARNING] Not passing the "--complete" option to "doctrine:schema:update" is deprecated and will
           not be supported when using doctrine/dbal 4   

Updating database schema...

     18 queries were executed

                                                                                                 
 [OK] Database schema updated successfully!

5. php bin/console bordeux:geoname:import  --env=prod

php bin/console bordeux:geoname:import  --env=prod

Start importing TimeZones from https://download.geonames.org/export/dump/timeZones.txt
100/100 [======================] 100% < 1 sec/< 1 sec Mem: 8.0 MiB Downloading data for TimeZones100/100 [==========================] 100% < 1 sec/< 1 sec Mem: 14.0 MiB Importing data: TimeZones
Finished importing TimeZones

Start importing Administrative from https://download.geonames.org/export/dump/admin1CodesASCII.txt
100/100 [================] 100% < 1 sec/< 1 sec Mem: 14.0 MiB Downloading data for Administrative100/100 [=====================] 100%  1 sec/1 sec  Mem: 26.0 MiB Importing data: Administrative
Finished importing Administrative

Start importing Administrative 2 from https://download.geonames.org/export/dump/admin2Codes.txt
100/100 [==============] 100% < 1 sec/< 1 sec Mem: 26.0 MiB Downloading data for Administrative 2100/100 [===================] 100% 4 secs/4 secs Mem: 48.0 MiB Importing data: Administrative 2
Finished importing Administrative 2

Start importing Administrative 2 from https://download.geonames.org/export/dump/admin2Codes.txt
100/100 [==============] 100% < 1 sec/< 1 sec Mem: 48.0 MiB Downloading data for Administrative 2100/100 [===================] 100% 3 secs/3 secs Mem: 48.0 MiB Importing data: Administrative 2
Finished importing Administrative 2

Start importing GeoNames from https://download.geonames.org/export/dump/allCountries.zip#allCountries.txt
100/100 [======================] 100% 19 secs/19 secs Mem: 48.0 MiB Downloading data for GeoNames  0/100 [>--------------------------]   0% < 1 sec/< 1 sec Mem: 48.0 MiB Importing data: GeoNames{"message":"Error thrown while running command \"bordeux:geoname:import --env=prod\". Message: \"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'geoname_id')::integer,\n                (_v.value->>'name'),\n              ...' at line 22\"","context":{"exception":{"class":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'geoname_id')::integer,\n                (_v.value->>'name'),\n              ...' at line 22","code":1064,"file":"/Users/pascal/PhpstormProjects/Elektra/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:86","previous":{"class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'geoname_id')::integer,\n                (_v.value->>'name'),\n              ...' at line 22","code":1064,"file":"/Users/pascal/PhpstormProjects/Elektra/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28","previous":{"class":"PDOException","message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'geoname_id')::integer,\n                (_v.value->>'name'),\n              ...' at line 22","code":42000,"file":"/Users/pascal/PhpstormProjects/Elektra/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:121"}}},"command":"bordeux:geoname:import --env=prod","message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'geoname_id')::integer,\n                (_v.value->>'name'),\n              ...' at line 22"},"level":500,"level_name":"CRITICAL","channel":"console","datetime":"2023-05-29T13:03:34.151985+00:00","extra":{}}

 An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'geoname_id')::integer,

**Comment by bordeux** [comment]
Hey @tiktoor  .
This bundle since version 3.0 supports only PostgreSQL databases.

Problem is with importing SQL statements. 
Insert statements are prepared only for PSQL which supporting JSON queries like this:
<img width="632" alt="image" src="https://github.com/bordeux/geoname-bundle/assets/784536/207e93e7-a001-4f40-a50f-f3aca8873b15">


This method allows to import entire database & update existing database with minutes.

**Comment by tiktoor** [comment]
Thank you for your very prompt answer, much appreciated! I will try to find my way towards a fitting solution.
