### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by treeindark** [bordeux/geoname-bundle#18]
`bordeux:geoname:import". Message: "An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 7 ERREUR:  la valeur « 2400000000 » est en dehors des limites pour le type integer" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 7): An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 7 ERREUR:  la valeur « **2400000000** » est en dehors des limites pour le type integer at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:87)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[22003]: Numeric value out of range: 7 ERREUR:  la valeur « 2400000000 » est en dehors des limites pour le type integer at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 7 ERREUR:  la valeur « 2400000000 » est en dehors des limites pour le type integer at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)","command":"bordeux:geoname:import","message":"An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 7 ERREUR:  la valeur « 2400000000 » est en dehors des limites pour le type integer"} []`

all int4 convert to int8, but... error,
found value 2400000000 in population? (int8) allcountry file

11812257        Commonwealth of Nations Commonwealth of Nations British Commonwealth of Nations 51.50488        -0.13602        A   ZN      GB AG,AU,BB,BD,BN,BS,BW,BZ,CA,CM,CY,DM,FJ,GB,GD,GH,GY,IN,JM,KE,KI,KN,LC,LK,LS,MT,MU,MW,MY,MZ,NA,NG,NR,NZ,PG,PK,RW,SB,SC,SG,SL,SZ,TO,TT,TV,TZ,UG,VC,VU,WS,ZA,ZM                                     2400000000              19      Europe/London   2018-09-02

**Comment by treeindark** [comment]
geo__name : 
`                                    Table « public.geo__name »
      Colonne      |          Type          | Collationnement | NULL-able |       Par défaut

-------------------+------------------------+-----------------+-----------+-------------------------
 id                | bigint                 |                 | not null  |
 country_id        | bigint                 |                 |           |
 admin1_id         | bigint                 |                 |           |
 admin2_id         | bigint                 |                 |           |
 admin3_id         | bigint                 |                 |           |
 admin4_id         | bigint                 |                 |           |
 timezone_id       | bigint                 |                 |           |
 name              | character varying(200) |                 | not null  |
 ascii_name        | character varying(200) |                 |           | NULL::character varying
 latitude          | double precision       |                 |           |
 longitude         | double precision       |                 |           |
 feature_class     | character varying(1)   |                 |           | NULL::character varying
 feature_code      | character varying(10)  |                 |           | NULL::character varying
 country_code      | character varying(2)   |                 |           | NULL::character varying
 cc2               | character varying(200) |                 |           | NULL::character varying
 population        | bigint                 |                 |           |
 elevation         | bigint                 |                 |           |
 dem               | bigint                 |                 |           |
 modification_date | date                   |                 |           |`


and search in log for 2400000000  : 
`":11812257,\"name\":\"Commonwealth of Nations\",\"asci_name\":\"Commonwealth of Nations\",\"alternate_names\":\"British Commonwealth of Nations\",\"latitude\":51.50488,\"longitude\":-0.13602,\"feature_class\":\"A\",\"feature_code\":\"ZN\",\"country_code\":\"GB\",\"cc2\":\"AG,AU,BB,BD,BN,BS,BW,BZ,CA,CM,CY,DM,FJ,GB,GD,GH,GY,IN,JM,KE,KI,KN,LC,LK,LS,MT,MU,MW,MY,MZ,NA,NG,NR,NZ,PG,PK,RW,SB,SC,SG,SL,SZ,TO,TT,TV,TZ,UG,VC,VU,WS,ZA,ZM\",\"admin1_code\":null,\"admin2_code\":null,\"admin3_code\":null,\"admin4_code\":null,\"population\":**2400000000**`

**Comment by bordeux** [comment]
@treeindark thank you for PR.

Released version 3.0.1 with your hotfix + 3.1.0 with your hotfix and update of CI/CD, and drop support for software out of EOL.
