### ISSUE TITLE
[WARNING] Some commands could not be registered

### ISSUE THREAD

**Issue by artemchalenko** [bordeux/geoname-bundle#3]
I have a problem with command `php bin/console bordeux:geoname:import`

`Type error: Argument 4 passed to Symfony\Component\Console\Input\InputOption::__construct() must be of the type string, null given, called in /var/www/vendor/symfony/console/Command/Command.php on line 388`

but problem was fixed into the master branch but not included to the last version.

It possible to publish new version of bundle?

**Comment by bordeux** [comment]
Released :) Thank you for support

**Comment by artemchalenko** [comment]
Thank you!
