### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by tiktoor** [bordeux/geoname-bundle#5]
Could you please update your code to match symfony 5 compatibility?

`composer require bordeux/geoname-bundle
Using version ^1.5 for bordeux/geoname-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bordeux/geoname-bundle ^1.5 -> satisfiable by bordeux/geoname-bundle[v1.5].
    - bordeux/geoname-bundle v1.5 requires symfony/framework-bundle ~2.7|~3.0|~4.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
`

**Comment by bordeux** [comment]
Package have been updated, with version 3.0 all issues have been fixed
